---
- name: Install kernel image package
  become: true
  apt:
    deb: "{{ kernel_image_deb }}"

- name: Install debug kernel image package
  become: true
  apt:
    deb: "{{ kernel_debug_deb }}"

- name: Install kernel headers package
  become: true
  apt:
    deb: "{{ kernel_headers_deb }}"

- name: Install kernel firmware image package
  become: true
  apt:
    deb: "{{ kernel_firmware_deb }}"
