---
- hosts: all
  vars:
    - eve_keyboard_assistant_keycode: rightmeta # Right "super" key
  tasks:

 ### blacklist intel sound module (required for audio)
    - name: Copy module blacklist file
      become: true
      copy:
        src: files/lib/modprobe.d/blacklist.conf
        dest: /lib/modprobe.d


 ### touchpad tweak

    - name: Ensure /etc/libinput exists
      become: true
      file:
        path: /etc/libinput
        state: directory

    - name: Copy touchpad pressure tweak file
      become: true
      copy:
        src: files/etc/libinput/local-overrides.quirks
        dest: /etc/libinput/local-overrides.quirks

### keyboard backlight

    - name: Ensure "leds" group exists
      group:
        name: leds

    - name: Ensure login user is in "leds" group
      become: true
      command: "usermod -aG leds {{ login_user }}"

    - name: Copy pixelbook udev rules file
      become: true
      copy:
        src: files/lib/udev/rules.d/99-pixelbook.rules
        dest: /lib/udev/rules.d

    - name: Copy brightness control script
      become: true
      copy:
        src: files/usr/local/bin/eve-keyboard-brightness.sh
        dest: /usr/local/bin
        mode: 0755


### Map google assistant key to super
#
#   note: change eve_keyboard_assistant_keycode var if you want a 
#   different keycode for the google assistant key

    - name: Copy keyboard hwdb file to remap assistant key
      become: true
      template:
        src: templates/61-eve-keyboard.hwdb.j2
        dest: /lib/udev/hwdb.d/61-eve-keyboard.hwdb
        mode: 0600
        owner: root
        group: root
