---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Create working dir to build packages
      become: true
      file:
        path: "{{ main_workdir }}"
        mode: 0777
        state: directory

 #### Copy files from eve recovery image 

    - name: Download eve recovery image
      get_url:
        url: "https://dl.google.com/dl/edgedl/chromeos/recovery/{{ eve_recovery_image }}.zip"
        dest: "{{ main_workdir }}/eve-recovery.zip"
        checksum: "sha256:{{ eve_recovery_image_sha256 }}"

    - name: Check if we've unzipped recovery image
      register: image_unzipped
      stat:
        path: "{{ main_workdir }}/{{ eve_recovery_image }}"

    - name: Unzip recovery image
      when: image_unzipped.stat.exists == False
      unarchive:
        src: "{{ main_workdir }}/eve-recovery.zip"
        dest: "{{ main_workdir }}"
        remote_src: yes

    - name: Map recovery image to loopback device
      become: true
      command: "kpartx -av {{ main_workdir }}/{{ eve_recovery_image }}"
      register: kpartx_output
      args:
        creates: /dev/mapper/loop8p3

    - name: Create mount point
      file:
        path: "{{ recovery_mount_point }}"
        state: directory

    - name: Mount recovery image
      become: true
      mount:
        path: "{{ recovery_mount_point }}"
        src: /dev/mapper/loop8p3
        fstype: ext2
        opts: ro
        state: mounted

    - name: Ensure /opt/google exists
      become: true
      file:
        path: /opt/google
        state: directory

    - name: Copy files from /opt/google on recovery image
      become: true
      command: "rsync -av {{ recovery_mount_point }}/opt/google/{{ item }} /opt/google"
      with_items:
        - disk
        - dsm
        - kbl-rt5514-hotword-support 
        - touch

    - name: Copy all firmware files from recovery image to /lib/firmware
      become: true
      command: "rsync -av {{ recovery_mount_point }}/lib/firmware/ /lib/firmware/"

    - name: Ensure /usr/share/alsa/ucm exists
      become: true
      file:
        path: /usr/share/alsa/ucm
        state: directory

    - name: Copy the alsa UCM configuration for eve's soundcard from recovery image
      become: true
      command: "rsync -av {{ recovery_mount_point }}/usr/share/alsa/ucm/kbl_r5514_5663_max /usr/share/alsa/ucm"


    - name: Copy cras souncard config files from recovery image
      become: true
      command: "rsync -av {{ recovery_mount_point }}/etc/cras {{ cras_etc_dir }}"

    - name: Unmount recovery image
      become: true
      mount:
        path: "{{ recovery_mount_point }}"
        state: absent
 
