---
- hosts: all
  vars:
    - main_workdir: /opt/eve-linux/setup

  tasks:
    - name: Install dev dependencies
      become: true
      dnf:
        name:
          # essential build tools (gcc, make, etc)
          - "@development-tools"
          - libtool
          - python
          - python3

          # For bluetooth selinux fix
          - selinux-policy
          - python2-libselinux

          # Audio / CRAS dependencies
          - acpid
          - libudev-devel
          - sbc-devel
          - alsa-lib-devel
          - iniparser-devel
          - ladspa-devel
          - speex-devel
          - speexdsp-devel
        state: latest 

    - name: Create working dir to build packages
      become: true
      file:
        path: "{{ main_workdir }}"
        mode: 0777
        state: directory

