---
- hosts: all

  tasks:
  - name: Install pre-requisites 
    include_role:
      name: common 

  - name: Extract files from eve recovery image
    include_role:
      name: eve-recovery-files

  - name: Install chromium fork of linux kernel
    include_role: 
      name: eve-kernel

  - name: Install Chrome Audio Server and sound setup files
    include_role:
      name: eve-audio

  #- name: Install misc tweaks
  #  include_role: eve-tweaks
